services:
  _defaults:
    tags: [ console.command ]

  fop.console.cache.clear.command:
    class: FOP\Console\Commands\Cache\CacheClear

  fop.console.category.clean.command:
    class: FOP\Console\Commands\Category\CategoryClean

  fop.console.category.products_count.command:
    class: FOP\Console\Commands\Category\CategoryProductsCount

  fop.console.configuration.export.command:
    class: FOP\Console\Commands\Configuration\ConfigurationExport

  fop.console.configuration.import.command:
    class: FOP\Console\Commands\Configuration\ConfigurationImport

  fop.console.container.check.command:
    class: FOP\Console\Commands\Container\ContainerCheck

  fop.console.employee.list.command:
    class: FOP\Console\Commands\Employee\EmployeeList

  fop.console.employee.change_password.command:
    class: FOP\Console\Commands\Employee\EmployeeChangePassword

  fop.console.environment.debug.command:
    class: FOP\Console\Commands\Environment\EnvironmentDebug

  fop.console.environment.get_parameters.command:
    class: FOP\Console\Commands\Environment\EnvironmentGetParameters

  fop.console.environment.setup_dev.command:
    class: FOP\Console\Commands\Environment\EnvironmentSetupDev

  fop.console.export.data.command:
    class: FOP\Console\Commands\Export\ExportData

  fop.console.generate.htaccess.command:
    class: FOP\Console\Commands\Generate\GenerateHtaccess

  fop.console.generate.robots.command:
    class: FOP\Console\Commands\Generate\GenerateRobots

  fop.console.group.transfer_customers.command:
    class: FOP\Console\Commands\Group\GroupTransferCustomers

  fop.console.hook.add.command:
    class: FOP\Console\Commands\Hook\HookAdd

  fop.console.image.generate_products.command:
    class: FOP\Console\Commands\Image\ImageGenerateProducts

  fop.console.image.generate_categories.command:
    class: FOP\Console\Commands\Image\ImageGenerateCategories

  fop.console.image.generate_manufacturers.command:
    class: FOP\Console\Commands\Image\ImageGenerateManufacturers

  fop.console.image.generate_suppliers.command:
    class: FOP\Console\Commands\Image\ImageGenerateSuppliers

  fop.console.image.generate_stores.command:
    class: FOP\Console\Commands\Image\ImageGenerateStores

  fop.console.module.unhook.command:
    class: FOP\Console\Commands\Module\ModuleUnhook

  fop.console.module.hook.command:
    class: FOP\Console\Commands\Module\ModuleHook

  fop.console.module.hooks.command:
    class: FOP\Console\Commands\Module\ModuleHooks

  fop.console.module.rename.command:
    class: FOP\Console\Commands\Module\ModuleRename

  fop.console.module.non_essential.command:
    class: FOP\Console\Commands\Module\ModuleNonEssential

  fop.console.module.generate.command:
    class: FOP\Console\Commands\Module\ModuleGenerate

  fop.console.override.make.command:
    class: FOP\Console\Commands\Override\OverrideMake

  fop.console.product.latest.command:
    class: FOP\Console\Commands\Product\ProductLatest

  fop.console.shop.status.command:
    class: FOP\Console\Commands\Shop\ShopStatus

  fop.console.shop.maintenance.command:
    class: FOP\Console\Commands\Shop\ShopMaintenance

  fop.console.theme.reset_layout.command:
    class: FOP\Console\Commands\Theme\ThemeResetLayout

  fop.console.about.version.command:
    class: FOP\Console\Commands\About\AboutVersion

  fop.console.log.clean.command:
    class: FOP\Console\Commands\Log\LogClean
