name: PHPStan
on: [ push, pull_request ]
jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache vendor folder
        uses: actions/cache@v4
        with:
          path: vendor
          key: php-8.3-${{ hashFiles('composer.lock') }}

      - name: Cache composer folder
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: php-composer-cache

      - name: Cache Prestashop source code
        id: cache_prestashop_source
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}/prestashop/
          key: ${{ runner.os }}-prestashop-9.1.5

      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name : "Install module dependencies"
        run: composer install

      - name: "Checkout PrestaShop 9.1.5"
        if: steps.cache_prestashop_source.outputs.cache-hit != 'true'
        run: git clone --branch 9.1.5 --depth 1 https://github.com/PrestaShop/PrestaShop.git ${{ runner.temp }}/prestashop

      - name: "Install PrestaShop dependencies"
        working-directory: ${{ runner.temp }}/prestashop
        run: composer install --no-dev --no-interaction --prefer-dist

      - name: "Run phpstan"
        run: _PS_ROOT_DIR_=${{ runner.temp }}/prestashop/ php ./vendor/bin/phpstan analyse ./
